[
{
    "domain": ".instagram.com",
    "expirationDate": 1811339627.803592,
    "hostOnly": false,
    "httpOnly": false,
    "name": "csrftoken",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "qkLf51cmOWNA4orE7JwIYWMC9Yu5wF7I",
    "id": 1
},
{
    "domain": ".instagram.com",
    "expirationDate": 1809438778.957694,
    "hostOnly": false,
    "httpOnly": true,
    "name": "datr",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "OoDKaXIM0RF6KX_i0mPh0edP",
    "id": 2
},
{
    "domain": ".instagram.com",
    "expirationDate": 1784555627.803769,
    "hostOnly": false,
    "httpOnly": false,
    "name": "ds_user_id",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "33222274408",
    "id": 3
},
{
    "domain": ".instagram.com",
    "expirationDate": 1806414778.957705,
    "hostOnly": false,
    "httpOnly": true,
    "name": "ig_did",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "1BF37491-BE65-45FA-91B6-005FD1318312",
    "id": 4
},
{
    "domain": ".instagram.com",
    "expirationDate": 1809438778.957715,
    "hostOnly": false,
    "httpOnly": true,
    "name": "mid",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "acqAOgAEAAFUpmmcwf8pRQCicFDM",
    "id": 5
},
{
    "domain": ".instagram.com",
    "expirationDate": 1809574060.992112,
    "hostOnly": false,
    "httpOnly": true,
    "name": "ps_l",
    "path": "/",
    "sameSite": "lax",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "1",
    "id": 6
},
{
    "domain": ".instagram.com",
    "expirationDate": 1809574060.992256,
    "hostOnly": false,
    "httpOnly": true,
    "name": "ps_n",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "1",
    "id": 7
},
{
    "domain": ".instagram.com",
    "hostOnly": false,
    "httpOnly": true,
    "name": "rur",
    "path": "/",
    "sameSite": "lax",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "\"EAG\\05433222274408\\0541808315627:01fe785b3a9777d1bdfe7d35e1116b6cb77223c8e0fc3984281b01aa5fd1e48675927aa8\"",
    "id": 8
},
{
    "domain": ".instagram.com",
    "expirationDate": 1808030744.882205,
    "hostOnly": false,
    "httpOnly": true,
    "name": "sessionid",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "33222274408%3AGqHlgK2n8wTpos%3A29%3AAYgvfyvTIvxZlE9O5dI9RGMzmyghVMhn1Vc1gcNlkg",
    "id": 9
},
{
    "domain": ".instagram.com",
    "expirationDate": 1777384420,
    "hostOnly": false,
    "httpOnly": false,
    "name": "wd",
    "path": "/",
    "sameSite": "lax",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "1710x985",
    "id": 10
}
]
